openapi: 3.1.0
info:
  contact:
    name: Kong, Inc.
  description: |
    KongAir Customer Information service provides customer information
    (payment methods, contact info, frequent flyer, etc...)
  version: 0.1.0
  title: Customer Information Service

servers:
- url: <KONG PROXY URL> ## ADDRESS OF GATEWAY FROM OPS TEAM
  description: Kong Proxy

x-kong-service-defaults:
  host: <Strigo Lab FQDN> ## FQDN FROM OPS TEAM
  port: <change me>
  protocol: http

paths:
  "/customer":
    get:
      summary: Fetch a customers information
      description: Fetch a customers information
      tags:
      - sales
      - customer
      operationId: get-cust-info
      responses:
        '200':
          $ref: '#/components/responses/CustomerSingle'
        '404':
          description: Customer Not Found
    options:
      summary: Preflight request for CORS
      description: |
        Handles the CORS preflight request for the /customer endpoint.
      tags:
      - sales
      - customer
      operationId: options-customer
      responses:
        '204':
          description: No Content - CORS preflight successful
          headers:
            Access-Control-Allow-Origin:
              description: Allowed origins for the endpoint.
              schema:
                type: string
            Access-Control-Allow-Methods:
              description: Allowed methods for the endpoint.
              schema:
                type: string
            Access-Control-Allow-Headers:
              description: Allowed headers for the endpoint.
              schema:
                type: string

components:
  responses:
    CustomerSingle:
      description: A get action response for a single Customer
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Customer'
  schemas:
    PaymentMethod:
      type: object
      properties:
        id:
          type: string
        redacted_card_number:
          type: string
        card_holder_name:
          type: string
        expiration-date:
          type: string
    CustomerInformation:
      type: object
      properties:
        address:
          type: string
        phone_number:
          type: string
        email:
          type: string
        frequent_flier_number:
          type: string
        payment_methods:
          type: array
          items:
            $ref: '#/components/schemas/PaymentMethod'
    Customer:
      type: object
      properties:
        id:
          type: string
        username:
          type: string
        name:
          type: string
        information:
          $ref: '#/components/schemas/CustomerInformation'

  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: apiKey

security:
  - ApiKeyAuth: []
