---
# OpenAPI Spec for the KongAir Bookings service
openapi: 3.1.0

info:
  description: KongAir Bookings service provides customers the ability to book and retrieve flight bookings on KongAir
  version: 0.1.0
  title: Bookings Service

servers:
- url: <KONG PROXY URL> ## ADDRESS OF GATEWAY FROM OPS TEAM
  description: Kong Proxy

x-kong-service-defaults:
  host: <Strigo Lab FQDN> ## FQDN FROM OPS TEAM
  port: <change me>
  protocol: http

paths:
  "/bookings":
    get:
      tags:
      - sales
      summary: Get a customers current bookings
      operationId: get-bookings
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Booking'
              examples:
                Example Bookings list response:
                  value: |
                    [{
                      "ticket_number": "CDF3412",
                      "seat": "32A",
                      "flight": {
                        "number": "KA924",
                        "route_id": "LHR-SFO",
                        "scheduled_departure": "2023-09-03T09:15:00Z",
                        "scheduled_arrival": "2023-09-03T14:23:00Z"
                      }
                    }]
        '401':
          description: Unauthorized
    post:
      tags:
        - sales
      summary: Create a new customer booking
      operationId: post-booking
      responses:
        '201':
          description: Booking Created Successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookingResponse'
              examples:
                Example new booking response body:
                  value: |
                   {
                    "ticket_number": "CDF3412"
                   }
        '401':
          description: Unauthorized
        '404':
          description: Not Found, likely for the flight_number given
          content:
            text/plain:
              schema:
                type: string
              example: Not found
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BookingRequest'
            examples:
              Example new booking request body:
                value: |
                 {
                   "flight_number": "KA924",
                   "seat": "32A"
                 }
    options:
      summary: Preflight request for CORS
      description: |
        Handles the CORS preflight request for the /bookings endpoint.
      tags:
      - sales
      operationId: options-bookings
      responses:
        '204':
          description: No Content - CORS preflight successful
          headers:
            Access-Control-Allow-Origin:
              description: Allowed origins for the endpoint.
              schema:
                type: string
            Access-Control-Allow-Methods:
              description: Allowed methods for the endpoint.
              schema:
                type: string
            Access-Control-Allow-Headers:
              description: Allowed headers for the endpoint.
              schema:
                type: string

components:
  schemas:
    Booking:
      type: object
      properties:
        ticket_number:
          type: string
        flight:
          type: object
          properties:
            number:
              type: string
            route_id:
              type: string
            scheduled_departure:
              type: string
              format: date-time
            scheduled_arrival:
              type: string
              format: date-time
        seat:
          type: string
      required:
        - ticket_number
        - flight
    BookingRequest:
      type: object
      properties:
        flight_number:
          type: string
        seat:
          type: string
      required:
        - flight_number
    BookingResponse:
      type: object
      properties:
        ticket_number:
          type: string
      required:
        - ticket_number